#!/usr/bin/env python3
"""Bake the mic button to depth-shaded RGB565A8 images (idle + recording).

The runtime button is a flat vertical gradient: no highlight, no rim, no glow,
because a box-shadow is what froze the device (a 35 KB corner buffer LVGL could
not allocate). A pre-rendered image gives all three back with zero runtime
allocation -- LVGL just blits it from flash.

Format is RGB565A8, same reasoning as the background: the colour plane is
Floyd-Steinberg dithered so the gradient does not band in 16-bit, and a separate
8-bit alpha plane carries the anti-aliased circle edge and the soft outer glow
so the button composites cleanly over the dithered background.

    python3 tools/bake_button.py main/assets/btn_mic.c
"""
import math
import sys

D = 228            # matches BTN_D
CX = CY = D / 2.0
R = 98.0           # circle radius; the rest of the box is glow margin
GLOW = 26.0        # soft glow reach beyond the rim

# (name, top, bottom, glow) -- top/bottom drive the vertical body gradient,
# lightened further toward the top by the radial sheen below.
VARIANTS = [
    ("btn_idle", (0x84, 0xFF, 0xC8), (0x14, 0x8A, 0x54), (0x3D, 0xDC, 0x97)),
    ("btn_rec",  (0xFF, 0x9A, 0x8E), (0xC1, 0x2A, 0x1E), (0xFF, 0x6E, 0x5E)),
]


def lerp(a, b, f):
    return tuple(a[i] + (b[i] - a[i]) * f for i in range(3))


def clamp(v, lo=0.0, hi=255.0):
    return max(lo, min(hi, v))


def shade(x, y, top, bot, glow):
    """Return (r,g,b,a) at (x,y) for one button, all 0..255, pre-dither."""
    dx, dy = x - CX, y - CY
    d = math.hypot(dx, dy)

    if d > R + GLOW:
        return (0.0, 0.0, 0.0, 0.0)

    # --- outside the disc: soft coloured glow ---
    if d > R:
        t = (d - R) / GLOW               # 0 at rim, 1 at glow edge
        a = (1.0 - t) ** 2 * 90.0        # falloff, max ~90/255
        return (glow[0], glow[1], glow[2], a)

    # --- inside the disc ---
    # 1. vertical body gradient, top lighter
    ty = (y - (CY - R)) / (2 * R)
    r, g, b = lerp(top, bot, clamp(ty, 0.0, 1.0))

    # 2. radial sheen: brighter toward the upper-centre, like a lit sphere.
    #    Sample point sits above centre so the highlight reads as a top-lit dome.
    sheen = 1.0 - math.hypot(dx, dy + R * 0.28) / (R * 1.35)
    sheen = clamp(sheen, 0.0, 1.0) ** 1.6
    r += (255 - r) * sheen * 0.35
    g += (255 - g) * sheen * 0.35
    b += (255 - b) * sheen * 0.35

    # 3. specular pip: a small soft ellipse of near-white near the top.
    sx, sy = dx / 34.0, (dy + R * 0.42) / 22.0
    spec = math.exp(-(sx * sx + sy * sy) * 1.3)
    r += (255 - r) * spec * 0.55
    g += (255 - g) * spec * 0.55
    b += (255 - b) * spec * 0.55

    # 4. rim shade: darken the last few px so the edge reads as a rounded lip.
    rim = clamp((d - (R - 6.0)) / 6.0, 0.0, 1.0)
    dark = 0.30 * rim
    r *= (1.0 - dark)
    g *= (1.0 - dark)
    b *= (1.0 - dark)

    # 5. anti-aliased edge in alpha over the last 1.5 px
    a = 255.0 * clamp((R - d) / 1.5, 0.0, 1.0)
    a = max(a, 0.0)
    # inside the disc alpha should be full except the very edge
    if d < R - 1.5:
        a = 255.0
    return (clamp(r), clamp(g), clamp(b), a)


def to565(r, g, b):
    return ((int(r) & 0xF8) << 8) | ((int(g) & 0xFC) << 3) | (int(b) >> 3)


def bake_variant(top, bot, glow):
    # full-precision colour + alpha
    rgb = [[None] * D for _ in range(D)]
    alpha = bytearray(D * D)
    for y in range(D):
        for x in range(D):
            r, g, b, a = shade(x, y, top, bot, glow)
            rgb[y][x] = [r, g, b]
            alpha[y * D + x] = int(round(a))

    # Floyd-Steinberg dither the colour plane to the RGB565 grid.
    LEVELS = (32, 64, 32)

    def quant(v, levels):
        step = 255.0 / (levels - 1)
        return round(round(v / step) * step)

    rgb565 = []
    for y in range(D):
        for x in range(D):
            old = rgb[y][x]
            new = [quant(old[c], LEVELS[c]) for c in range(3)]
            err = [old[c] - new[c] for c in range(3)]
            rgb565.append(to565(*new))
            for dx, dy, w in ((1, 0, 7), (-1, 1, 3), (0, 1, 5), (1, 1, 1)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < D and 0 <= ny < D:
                    for c in range(3):
                        rgb[ny][nx][c] = clamp(rgb[ny][nx][c] + err[c] * w / 16.0)
    return rgb565, alpha


def emit(path):
    with open(path, "w") as f:
        f.write("/* GENERATED by tools/bake_button.py -- do not edit.\n")
        f.write(" * Depth-shaded mic button, RGB565 (dithered) + A8 alpha. */\n")
        f.write('#include "btn_mic.h"\n\n')
        for name, top, bot, glow in VARIANTS:
            rgb565, alpha = bake_variant(top, bot, glow)
            f.write("static const uint8_t %s_data[] = {\n" % name)
            row = []
            # RGB565 plane (little-endian), then the A8 plane appended.
            for p in rgb565:
                row += ["0x%02X" % (p & 0xFF), "0x%02X" % ((p >> 8) & 0xFF)]
                if len(row) >= 24:
                    f.write("    " + ",".join(row) + ",\n"); row = []
            for a in alpha:
                row.append("0x%02X" % a)
                if len(row) >= 24:
                    f.write("    " + ",".join(row) + ",\n"); row = []
            if row:
                f.write("    " + ",".join(row) + ",\n")
            f.write("};\n\n")
            f.write("const lv_image_dsc_t %s = {\n" % name)
            f.write("    .header = { .magic = LV_IMAGE_HEADER_MAGIC,\n")
            f.write("                .cf = LV_COLOR_FORMAT_RGB565A8,\n")
            f.write("                .w = %d, .h = %d, .stride = %d },\n" % (D, D, D * 2))
            f.write("    .data_size = sizeof(%s_data),\n" % name)
            f.write("    .data = %s_data,\n" % name)
            f.write("};\n\n")


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "main/assets/btn_mic.c"
    emit(out)
    print(f"wrote {out}: 2x {D}x{D} RGB565A8")
