#!/usr/bin/env python3
"""Bake a soft radial glow to an A8 alpha mask -- the animated halo.

The static halo baked into the background sits behind the button and the
spectrum and never reads as a glow. This is a separate element the firmware
places behind the button and breathes (opacity animated), recoloured to mint,
so it pulses as a visible halo.

    python3 tools/bake_halo.py main/assets/ic_halo.c

Needs Pillow.
"""
import math
import sys

from PIL import Image

W = H = 320


def draw():
    img = Image.new("L", (W, H), 0)
    px = img.load()
    cx = cy = W / 2.0
    r = W / 2.0
    for y in range(H):
        for x in range(W):
            d = math.hypot(x - cx, y - cy) / r
            if d >= 1.0:
                continue
            # smooth falloff, brightest in the middle; squared for a soft edge
            px[x, y] = int(255 * (1.0 - d) ** 2.2)
    return img


def emit(path, img):
    px = img.load()
    with open(path, "w") as f:
        f.write("/* GENERATED by tools/bake_halo.py -- do not edit.\n")
        f.write(" * Soft radial glow, A8 alpha (recoloured + opacity-animated). */\n")
        f.write('#include "ic_halo.h"\n\n')
        f.write("static const uint8_t ic_halo_data[] = {\n")
        row = []
        for y in range(H):
            for x in range(W):
                row.append("0x%02X" % px[x, y])
                if len(row) >= 24:
                    f.write("    " + ",".join(row) + ",\n"); row = []
        if row:
            f.write("    " + ",".join(row) + ",\n")
        f.write("};\n\n")
        f.write("const lv_image_dsc_t ic_halo = {\n")
        f.write("    .header = { .magic = LV_IMAGE_HEADER_MAGIC,\n")
        f.write("                .cf = LV_COLOR_FORMAT_A8,\n")
        f.write("                .w = %d, .h = %d, .stride = %d },\n" % (W, H, W))
        f.write("    .data_size = sizeof(ic_halo_data),\n")
        f.write("    .data = ic_halo_data,\n")
        f.write("};\n")


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "main/assets/ic_halo.c"
    emit(out, draw())
    print(f"wrote {out}: {W}x{H} A8 radial glow")
