#!/usr/bin/env python3
"""Bake a clean microphone glyph to an A8 alpha mask.

The on-device mic used to be four LVGL primitives (a capsule, an arc, two bars)
and looked like exactly that -- crude, hard-edged. This draws a filled mic at 4x
and downsamples with a good filter, so the edges are properly anti-aliased. The
output is an 8-bit alpha mask; LVGL recolors it to the ink colour at draw time,
so one image serves on both the green and red buttons.

    python3 tools/bake_mic.py main/assets/ic_mic.c

Needs Pillow (pip install pillow).
"""
import sys

from PIL import Image, ImageDraw

W, H = 96, 120
SS = 4  # supersample factor for anti-aliasing


def draw_mic():
    w, h = W * SS, H * SS
    img = Image.new("L", (w, h), 0)
    d = ImageDraw.Draw(img)

    cx = w / 2
    s = SS  # shorthand for scaling constants below

    # Body: a vertical capsule. rounded_rectangle with radius = half-width gives
    # fully round ends.
    body_w = 40 * s
    body_h = 60 * s
    bx0 = cx - body_w / 2
    by0 = 8 * s
    d.rounded_rectangle([bx0, by0, bx0 + body_w, by0 + body_h],
                        radius=body_w / 2, fill=255)

    # Cradle: a thick U-arc hugging the lower half of the body. draw.arc strokes
    # a circle segment; width gives it body. Angles are clockwise from 3 o'clock,
    # so 20..160 sweeps the bottom.
    cr = 34 * s
    cy = 40 * s
    d.arc([cx - cr, cy - cr, cx + cr, cy + cr],
          start=20, end=160, fill=255, width=int(7 * s))

    # Stem: from the bottom of the cradle down to the base.
    stem_w = 7 * s
    d.rounded_rectangle([cx - stem_w / 2, cy + cr - 3 * s, cx + stem_w / 2, 104 * s],
                        radius=stem_w / 2, fill=255)

    # Base: a short foot bar.
    base_w = 44 * s
    d.rounded_rectangle([cx - base_w / 2, 102 * s, cx + base_w / 2, 110 * s],
                        radius=4 * s, fill=255)

    return img.resize((W, H), Image.LANCZOS)


def emit(path, img):
    px = img.load()
    with open(path, "w") as f:
        f.write("/* GENERATED by tools/bake_mic.py -- do not edit.\n")
        f.write(" * Anti-aliased microphone, A8 alpha mask (recolour at draw time). */\n")
        f.write('#include "ic_mic.h"\n\n')
        f.write("static const uint8_t ic_mic_data[] = {\n")
        row = []
        for y in range(H):
            for x in range(W):
                row.append("0x%02X" % px[x, y])
                if len(row) >= 24:
                    f.write("    " + ",".join(row) + ",\n")
                    row = []
        if row:
            f.write("    " + ",".join(row) + ",\n")
        f.write("};\n\n")
        f.write("const lv_image_dsc_t ic_mic = {\n")
        f.write("    .header = { .magic = LV_IMAGE_HEADER_MAGIC,\n")
        f.write("                .cf = LV_COLOR_FORMAT_A8,\n")
        f.write("                .w = %d, .h = %d, .stride = %d },\n" % (W, H, W))
        f.write("    .data_size = sizeof(ic_mic_data),\n")
        f.write("    .data = ic_mic_data,\n")
        f.write("};\n")


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "main/assets/ic_mic.c"
    emit(out, draw_mic())
    print(f"wrote {out}: {W}x{H} A8")
