#!/usr/bin/env python3
"""Bake a clean microphone glyph to an A8 alpha mask.

The on-device mic used to be four LVGL primitives (a capsule, an arc, two bars)
and looked like exactly that -- crude, hard-edged. This draws a filled mic at 4x
and downsamples with a good filter, so the edges are properly anti-aliased. The
output is an 8-bit alpha mask; LVGL recolors it to the ink colour at draw time,
so one image serves on both the green and red buttons.

    python3 tools/bake_mic.py main/assets/ic_mic.c

Needs Pillow (pip install pillow).
"""
import sys

from PIL import Image, ImageDraw

W, H = 96, 120
SS = 4  # supersample factor for anti-aliasing


def draw_mic():
    w, h = W * SS, H * SS
    img = Image.new("L", (w, h), 0)
    d = ImageDraw.Draw(img)

    # Geometry mirrors the reference glyph in web/index.html: capsule 30x56
    # (r15) on y in [-44, 12], cradle = the bottom half of a radius-30 circle
    # centred at (0, -8) with a 6-unit round-capped stroke, stem 7x16, base
    # 34x6. Everything below is in those glyph units: one unit is K pixels,
    # and the glyph's 66x84 bounding box is centred on the canvas.
    K = 4 / 3 * SS
    ox, oy = w / 2, h / 2 + 2 * K  # bbox spans y in [-44, 40], so centre is -2

    def X(u):
        return ox + u * K

    def Y(v):
        return oy + v * K

    # Body: a vertical capsule. rounded_rectangle with radius = half-width gives
    # fully round ends.
    d.rounded_rectangle([X(-15), Y(-44), X(15), Y(12)], radius=15 * K, fill=255)

    # Cradle: a full 180-degree U-arc. draw.arc strokes inward from the bbox
    # ellipse, so the bbox sits at the stroke's outer edge (radius 30 + 3).
    # Angles are clockwise from 3 o'clock, so 0..180 sweeps the bottom. PIL has
    # no stroke-linecap="round"; filled discs at both stroke ends stand in.
    d.arc([X(-33), Y(-41), X(33), Y(25)], start=0, end=180,
          fill=255, width=round(6 * K))
    for ex in (-30, 30):
        d.ellipse([X(ex - 3), Y(-11), X(ex + 3), Y(-5)], fill=255)

    # Stem: from just inside the cradle's bottom down into the base.
    d.rounded_rectangle([X(-3.5), Y(20), X(3.5), Y(36)], radius=3 * K, fill=255)

    # Base: a short foot bar.
    d.rounded_rectangle([X(-17), Y(34), X(17), Y(40)], radius=3 * K, fill=255)

    return img.resize((W, H), Image.LANCZOS)


def emit(path, img):
    px = img.load()
    with open(path, "w") as f:
        f.write("/* GENERATED by tools/bake_mic.py -- do not edit.\n")
        f.write(" * Anti-aliased microphone, A8 alpha mask (recolour at draw time). */\n")
        f.write('#include "ic_mic.h"\n\n')
        f.write("static const uint8_t ic_mic_data[] = {\n")
        row = []
        for y in range(H):
            for x in range(W):
                row.append("0x%02X" % px[x, y])
                if len(row) >= 24:
                    f.write("    " + ",".join(row) + ",\n")
                    row = []
        if row:
            f.write("    " + ",".join(row) + ",\n")
        f.write("};\n\n")
        f.write("const lv_image_dsc_t ic_mic = {\n")
        f.write("    .header = { .magic = LV_IMAGE_HEADER_MAGIC,\n")
        f.write("                .cf = LV_COLOR_FORMAT_A8,\n")
        f.write("                .w = %d, .h = %d, .stride = %d },\n" % (W, H, W))
        f.write("    .data_size = sizeof(ic_mic_data),\n")
        f.write("    .data = ic_mic_data,\n")
        f.write("};\n")


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "main/assets/ic_mic.c"
    emit(out, draw_mic())
    print(f"wrote {out}: {W}x{H} A8")
