#!/usr/bin/env python3
"""Bake the main-screen background to a dithered RGB565 C array.

The runtime gradient bands: RGB565 has ~6 distinct blue levels across 448 px, and
LVGL 9 dropped the gradient dithering v8 had. So the ramp cannot be smooth in
that format unless we dither it ourselves, at build time, where we have the
whole image and unlimited precision.

Output is an lv_image_dsc_t the firmware sets as the screen's bg_image_src. It
lives in flash (.rodata) and LVGL draws straight from it -- no runtime gradient,
no per-chunk recompute, no malloc.

    python3 tools/bake_bg.py main/assets/bg_main.c
"""
import sys

import os
W = int(os.environ.get('BG_W', 368))
H = int(os.environ.get('BG_H', 448))

# The same four stops as the old runtime gradient (C_BG_0..3), as (frac, rgb).
STOPS = [
    (0.00, (0x00, 0x00, 0x00)),
    (0.47, (0x06, 0x0B, 0x12)),
    (0.80, (0x0D, 0x18, 0x26)),
    (1.00, (0x16, 0x28, 0x3A)),
]


def lerp(a, b, f):
    return tuple(a[i] + (b[i] - a[i]) * f for i in range(3))


def gradient_row(y):
    """The exact 8-bit-per-channel colour at row y, before dithering."""
    t = y / (H - 1)
    for i in range(len(STOPS) - 1):
        f0, c0 = STOPS[i]
        f1, c1 = STOPS[i + 1]
        if t <= f1 or i == len(STOPS) - 2:
            span = (t - f0) / (f1 - f0) if f1 > f0 else 0.0
            return lerp(c0, c1, max(0.0, min(1.0, span)))
    return STOPS[-1][1]


def to565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


# The mint halo that pools at the bottom-centre of the screen, the same accent
# the button and the web mockup use. Additive and soft, so it lifts the dark
# gradient without competing with the button sitting above it.
HALO_RGB = (0x3D, 0xDC, 0x97)
HALO_INTENSITY = 0.30    # peak green added, 0..1
HALO_CX = 0.5            # centre, as a fraction of width
HALO_CY = 1.02           # just below the bottom edge, so only the top of the glow shows
HALO_RX = 0.62           # radii as a fraction of width/height
HALO_RY = 0.42


def with_halo(x, y, base):
    dx = (x - HALO_CX * W) / (HALO_RX * W)
    dy = (y - HALO_CY * H) / (HALO_RY * H)
    d2 = dx * dx + dy * dy
    if d2 >= 1.0:
        return base
    g = HALO_INTENSITY * (1.0 - d2) ** 2  # smooth falloff to the rim
    return [min(255.0, base[c] + HALO_RGB[c] * g) for c in range(3)]


def bake():
    # Float image, then Floyd-Steinberg dither to the RGB565 grid. The error
    # diffusion is what replaces hard bands with imperceptible pixel noise.
    img = [[with_halo(x, y, list(gradient_row(y))) for x in range(W)] for y in range(H)]
    LEVELS = (32, 64, 32)  # 5/6/5 bits

    def quant(v, levels):
        step = 255.0 / (levels - 1)
        return round(round(v / step) * step)

    out = []
    for y in range(H):
        for x in range(W):
            old = img[y][x]
            new = [quant(old[c], LEVELS[c]) for c in range(3)]
            err = [old[c] - new[c] for c in range(3)]
            out.append(to565(*[max(0, min(255, int(round(v)))) for v in new]))
            # spread the quantisation error to neighbours (7/16, 3/16, 5/16, 1/16)
            for dx, dy, w in ((1, 0, 7), (-1, 1, 3), (0, 1, 5), (1, 1, 1)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < W and 0 <= ny < H:
                    for c in range(3):
                        img[ny][nx][c] += err[c] * w / 16.0
    return out


def emit(path, px):
    with open(path, "w") as f:
        f.write("/* GENERATED by tools/bake_bg.py -- do not edit.\n")
        f.write(" * Dithered RGB565 background for the main screen. */\n")
        f.write('#include "bg_main.h"\n\n')
        f.write("static const uint8_t bg_main_data[] = {\n")
        # LVGL RGB565 is little-endian uint16 per pixel.
        row = []
        for i, p in enumerate(px):
            row.append("0x%02X,0x%02X," % (p & 0xFF, (p >> 8) & 0xFF))
            if len(row) == 12:
                f.write("    " + "".join(row) + "\n")
                row = []
        if row:
            f.write("    " + "".join(row) + "\n")
        f.write("};\n\n")
        f.write("const lv_image_dsc_t bg_main = {\n")
        f.write("    .header = { .magic = LV_IMAGE_HEADER_MAGIC,\n")
        f.write("                .cf = LV_COLOR_FORMAT_RGB565,\n")
        f.write("                .w = %d, .h = %d, .stride = %d },\n" % (W, H, W * 2))
        f.write("    .data_size = sizeof(bg_main_data),\n")
        f.write("    .data = bg_main_data,\n")
        f.write("};\n")


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "main/assets/bg_main.c"
    emit(out, bake())
    print(f"wrote {out}: {W}x{H} RGB565, {W*H*2} bytes of pixel data")
