/* US Multinational Keyboard Layout (en-US).
 *
 * GENERATED by tools/gen_keymap.py — edit the generator, not this file.
 * Source: This file was automatically generated by http://kbdlayout.info/ based on KBDTABLES
 * Source: of US Multinational Keyboard Layout in kbdusx.dll version 10.0.25393.1.
 * via the KLC export of usintl.klc, scancodes translated to HID usages.
 *
 * The AltGr column matches Windows and Linux, which both treat Right
 * Alt as AltGr for this layout. macOS builds its Option combinations
 * differently; on a macOS host those entries may come out wrong until
 * validated.
 */
#include "core/keymap.h"

#define S HID_MOD_LSHIFT
#define G HID_MOD_RALT

#define ONE(cp, m, k) {(cp), {{{(m), (k)}}, 1}}
#define TWO(cp, m1, k1, m2, k2) {(cp), {{{(m1), (k1)}, {(m2), (k2)}}, 2}}

static const keymap_entry_t keymap_usintl_entries[] = {
    ONE('\t', 0, HID_KEY_TAB),
    ONE('\n', 0, HID_KEY_ENTER),
    ONE(' ', 0, 0x2C),
    ONE('!', S, 0x1E),
    TWO('"', S, 0x34, 0, 0x2C), /* ": dead " +   */
    ONE('#', S, 0x20),
    ONE('$', S, 0x21),
    ONE('%', S, 0x22),
    ONE('&', S, 0x24),
    TWO('\'', 0, 0x34, 0, 0x2C), /* ': dead ' +   */
    ONE('(', S, 0x26),
    ONE(')', S, 0x27),
    ONE('*', S, 0x25),
    ONE('+', S, 0x2E),
    ONE(',', 0, 0x36),
    ONE('-', 0, 0x2D),
    ONE('.', 0, 0x37),
    ONE('/', 0, 0x38),
    ONE('0', 0, 0x27),
    ONE('1', 0, 0x1E),
    ONE('2', 0, 0x1F),
    ONE('3', 0, 0x20),
    ONE('4', 0, 0x21),
    ONE('5', 0, 0x22),
    ONE('6', 0, 0x23),
    ONE('7', 0, 0x24),
    ONE('8', 0, 0x25),
    ONE('9', 0, 0x26),
    ONE(':', S, 0x33),
    ONE(';', 0, 0x33),
    ONE('<', S, 0x36),
    ONE('=', 0, 0x2E),
    ONE('>', S, 0x37),
    ONE('?', S, 0x38),
    ONE('@', S, 0x1F),
    ONE('A', S, 0x04),
    ONE('B', S, 0x05),
    ONE('C', S, 0x06),
    ONE('D', S, 0x07),
    ONE('E', S, 0x08),
    ONE('F', S, 0x09),
    ONE('G', S, 0x0A),
    ONE('H', S, 0x0B),
    ONE('I', S, 0x0C),
    ONE('J', S, 0x0D),
    ONE('K', S, 0x0E),
    ONE('L', S, 0x0F),
    ONE('M', S, 0x10),
    ONE('N', S, 0x11),
    ONE('O', S, 0x12),
    ONE('P', S, 0x13),
    ONE('Q', S, 0x14),
    ONE('R', S, 0x15),
    ONE('S', S, 0x16),
    ONE('T', S, 0x17),
    ONE('U', S, 0x18),
    ONE('V', S, 0x19),
    ONE('W', S, 0x1A),
    ONE('X', S, 0x1B),
    ONE('Y', S, 0x1C),
    ONE('Z', S, 0x1D),
    ONE('[', 0, 0x2F),
    ONE('\\', 0, 0x32),
    ONE(']', 0, 0x30),
    TWO('^', S, 0x23, 0, 0x2C), /* ^: dead ^ +   */
    ONE('_', S, 0x2D),
    TWO('`', 0, 0x35, 0, 0x2C), /* `: dead ` +   */
    ONE('a', 0, 0x04),
    ONE('b', 0, 0x05),
    ONE('c', 0, 0x06),
    ONE('d', 0, 0x07),
    ONE('e', 0, 0x08),
    ONE('f', 0, 0x09),
    ONE('g', 0, 0x0A),
    ONE('h', 0, 0x0B),
    ONE('i', 0, 0x0C),
    ONE('j', 0, 0x0D),
    ONE('k', 0, 0x0E),
    ONE('l', 0, 0x0F),
    ONE('m', 0, 0x10),
    ONE('n', 0, 0x11),
    ONE('o', 0, 0x12),
    ONE('p', 0, 0x13),
    ONE('q', 0, 0x14),
    ONE('r', 0, 0x15),
    ONE('s', 0, 0x16),
    ONE('t', 0, 0x17),
    ONE('u', 0, 0x18),
    ONE('v', 0, 0x19),
    ONE('w', 0, 0x1A),
    ONE('x', 0, 0x1B),
    ONE('y', 0, 0x1C),
    ONE('z', 0, 0x1D),
    ONE('{', S, 0x2F),
    ONE('|', S, 0x32),
    ONE('}', S, 0x30),
    TWO('~', S, 0x35, 0, 0x2C), /* ~: dead ~ +   */
    ONE(0x00A1, G, 0x1E), /* ¡ */
    ONE(0x00A2, S|G, 0x06), /* ¢ */
    ONE(0x00A3, S|G, 0x21), /* £ */
    ONE(0x00A4, G, 0x21), /* ¤ */
    ONE(0x00A5, G, 0x2D), /* ¥ */
    ONE(0x00A6, S|G, 0x32), /* ¦ */
    ONE(0x00A7, S|G, 0x16), /* § */
    ONE(0x00A8, S|G, 0x34), /* ¨ */
    ONE(0x00A9, G, 0x06), /* © */
    ONE(0x00AB, G, 0x2F), /* « */
    ONE(0x00AC, G, 0x32), /* ¬ */
    ONE(0x00AE, G, 0x15), /* ® */
    ONE(0x00B0, S|G, 0x33), /* ° */
    ONE(0x00B2, G, 0x1F), /* ² */
    ONE(0x00B3, G, 0x20), /* ³ */
    ONE(0x00B4, G, 0x34), /* ´ */
    ONE(0x00B5, G, 0x10), /* µ */
    ONE(0x00B6, G, 0x33), /* ¶ */
    ONE(0x00B9, S|G, 0x1E), /* ¹ */
    ONE(0x00BB, G, 0x30), /* » */
    ONE(0x00BC, G, 0x23), /* ¼ */
    ONE(0x00BD, G, 0x24), /* ½ */
    ONE(0x00BE, G, 0x25), /* ¾ */
    ONE(0x00BF, G, 0x38), /* ¿ */
    TWO(0x00C0, 0, 0x35, S, 0x04), /* À: dead ` + A */
    ONE(0x00C1, S|G, 0x04), /* Á */
    TWO(0x00C2, S, 0x23, S, 0x04), /* Â: dead ^ + A */
    TWO(0x00C3, S, 0x35, S, 0x04), /* Ã: dead ~ + A */
    ONE(0x00C4, S|G, 0x14), /* Ä */
    ONE(0x00C5, S|G, 0x1A), /* Å */
    ONE(0x00C6, S|G, 0x1D), /* Æ */
    ONE(0x00C7, S|G, 0x36), /* Ç */
    TWO(0x00C8, 0, 0x35, S, 0x08), /* È: dead ` + E */
    ONE(0x00C9, S|G, 0x08), /* É */
    TWO(0x00CA, S, 0x23, S, 0x08), /* Ê: dead ^ + E */
    TWO(0x00CB, S, 0x34, S, 0x08), /* Ë: dead " + E */
    TWO(0x00CC, 0, 0x35, S, 0x0C), /* Ì: dead ` + I */
    ONE(0x00CD, S|G, 0x0C), /* Í */
    TWO(0x00CE, S, 0x23, S, 0x0C), /* Î: dead ^ + I */
    TWO(0x00CF, S, 0x34, S, 0x0C), /* Ï: dead " + I */
    ONE(0x00D0, S|G, 0x07), /* Ð */
    ONE(0x00D1, S|G, 0x11), /* Ñ */
    TWO(0x00D2, 0, 0x35, S, 0x12), /* Ò: dead ` + O */
    ONE(0x00D3, S|G, 0x12), /* Ó */
    TWO(0x00D4, S, 0x23, S, 0x12), /* Ô: dead ^ + O */
    TWO(0x00D5, S, 0x35, S, 0x12), /* Õ: dead ~ + O */
    ONE(0x00D6, S|G, 0x13), /* Ö */
    ONE(0x00D7, G, 0x2E), /* × */
    ONE(0x00D8, S|G, 0x0F), /* Ø */
    TWO(0x00D9, 0, 0x35, S, 0x18), /* Ù: dead ` + U */
    ONE(0x00DA, S|G, 0x18), /* Ú */
    TWO(0x00DB, S, 0x23, S, 0x18), /* Û: dead ^ + U */
    ONE(0x00DC, S|G, 0x1C), /* Ü */
    TWO(0x00DD, 0, 0x34, S, 0x1C), /* Ý: dead ' + Y */
    ONE(0x00DE, S|G, 0x17), /* Þ */
    ONE(0x00DF, G, 0x16), /* ß */
    TWO(0x00E0, 0, 0x35, 0, 0x04), /* à: dead ` + a */
    ONE(0x00E1, G, 0x04), /* á */
    TWO(0x00E2, S, 0x23, 0, 0x04), /* â: dead ^ + a */
    TWO(0x00E3, S, 0x35, 0, 0x04), /* ã: dead ~ + a */
    ONE(0x00E4, G, 0x14), /* ä */
    ONE(0x00E5, G, 0x1A), /* å */
    ONE(0x00E6, G, 0x1D), /* æ */
    ONE(0x00E7, G, 0x36), /* ç */
    TWO(0x00E8, 0, 0x35, 0, 0x08), /* è: dead ` + e */
    ONE(0x00E9, G, 0x08), /* é */
    TWO(0x00EA, S, 0x23, 0, 0x08), /* ê: dead ^ + e */
    TWO(0x00EB, S, 0x34, 0, 0x08), /* ë: dead " + e */
    TWO(0x00EC, 0, 0x35, 0, 0x0C), /* ì: dead ` + i */
    ONE(0x00ED, G, 0x0C), /* í */
    TWO(0x00EE, S, 0x23, 0, 0x0C), /* î: dead ^ + i */
    TWO(0x00EF, S, 0x34, 0, 0x0C), /* ï: dead " + i */
    ONE(0x00F0, G, 0x07), /* ð */
    ONE(0x00F1, G, 0x11), /* ñ */
    TWO(0x00F2, 0, 0x35, 0, 0x12), /* ò: dead ` + o */
    ONE(0x00F3, G, 0x12), /* ó */
    TWO(0x00F4, S, 0x23, 0, 0x12), /* ô: dead ^ + o */
    TWO(0x00F5, S, 0x35, 0, 0x12), /* õ: dead ~ + o */
    ONE(0x00F6, G, 0x13), /* ö */
    ONE(0x00F7, S|G, 0x2E), /* ÷ */
    ONE(0x00F8, G, 0x0F), /* ø */
    TWO(0x00F9, 0, 0x35, 0, 0x18), /* ù: dead ` + u */
    ONE(0x00FA, G, 0x18), /* ú */
    TWO(0x00FB, S, 0x23, 0, 0x18), /* û: dead ^ + u */
    ONE(0x00FC, G, 0x1C), /* ü */
    TWO(0x00FD, 0, 0x34, 0, 0x1C), /* ý: dead ' + y */
    ONE(0x00FE, G, 0x17), /* þ */
    TWO(0x00FF, S, 0x34, 0, 0x1C), /* ÿ: dead " + y */
    ONE(0x2018, G, 0x26), /* ‘ */
    ONE(0x2019, G, 0x27), /* ’ */
    ONE(0x20AC, G, 0x22), /* € */
};

static bool keymap_usintl_lookup(uint32_t cp, hid_seq_t *out)
{
    return keymap_table_lookup(keymap_usintl_entries,
                               sizeof(keymap_usintl_entries) / sizeof(keymap_usintl_entries[0]), cp, out);
}

const keymap_layout_t keymap_usintl = {
    .name   = "us-intl",
    .lookup = keymap_usintl_lookup,
};
