/* French Keyboard Layout (fr-FR).
 *
 * GENERATED by tools/gen_keymap.py — edit the generator, not this file.
 * Source: This file was automatically generated by http://kbdlayout.info/ based on KBDTABLES
 * Source: of French Keyboard Layout in kbdfr.dll version 10.0.25393.1.
 * via the KLC export of fr.klc, scancodes translated to HID usages.
 *
 * The AltGr column matches Windows and Linux, which both treat Right
 * Alt as AltGr for this layout. macOS builds its Option combinations
 * differently; on a macOS host those entries may come out wrong until
 * validated.
 */
#include "core/keymap.h"

#define S HID_MOD_LSHIFT
#define G HID_MOD_RALT

#define ONE(cp, m, k) {(cp), {{{(m), (k)}}, 1}}
#define TWO(cp, m1, k1, m2, k2) {(cp), {{{(m1), (k1)}, {(m2), (k2)}}, 2}}

static const keymap_entry_t keymap_fr_entries[] = {
    ONE('\t', 0, HID_KEY_TAB),
    ONE('\n', 0, HID_KEY_ENTER),
    ONE(' ', 0, 0x2C),
    ONE('!', 0, 0x38),
    ONE('"', 0, 0x20),
    ONE('#', G, 0x20),
    ONE('$', 0, 0x30),
    ONE('%', S, 0x34),
    ONE('&', 0, 0x1E),
    ONE('\'', 0, 0x21),
    ONE('(', 0, 0x22),
    ONE(')', 0, 0x2D),
    ONE('*', 0, 0x32),
    ONE('+', S, 0x2E),
    ONE(',', 0, 0x10),
    ONE('-', 0, 0x23),
    ONE('.', S, 0x36),
    ONE('/', S, 0x37),
    ONE('0', S, 0x27),
    ONE('1', S, 0x1E),
    ONE('2', S, 0x1F),
    ONE('3', S, 0x20),
    ONE('4', S, 0x21),
    ONE('5', S, 0x22),
    ONE('6', S, 0x23),
    ONE('7', S, 0x24),
    ONE('8', S, 0x25),
    ONE('9', S, 0x26),
    ONE(':', 0, 0x37),
    ONE(';', 0, 0x36),
    ONE('<', 0, 0x64),
    ONE('=', 0, 0x2E),
    ONE('>', S, 0x64),
    ONE('?', S, 0x10),
    ONE('@', G, 0x27),
    ONE('A', S, 0x14),
    ONE('B', S, 0x05),
    ONE('C', S, 0x06),
    ONE('D', S, 0x07),
    ONE('E', S, 0x08),
    ONE('F', S, 0x09),
    ONE('G', S, 0x0A),
    ONE('H', S, 0x0B),
    ONE('I', S, 0x0C),
    ONE('J', S, 0x0D),
    ONE('K', S, 0x0E),
    ONE('L', S, 0x0F),
    ONE('M', S, 0x33),
    ONE('N', S, 0x11),
    ONE('O', S, 0x12),
    ONE('P', S, 0x13),
    ONE('Q', S, 0x04),
    ONE('R', S, 0x15),
    ONE('S', S, 0x16),
    ONE('T', S, 0x17),
    ONE('U', S, 0x18),
    ONE('V', S, 0x19),
    ONE('W', S, 0x1D),
    ONE('X', S, 0x1B),
    ONE('Y', S, 0x1C),
    ONE('Z', S, 0x1A),
    ONE('[', G, 0x22),
    ONE('\\', G, 0x25),
    ONE(']', G, 0x2D),
    ONE('^', G, 0x26),
    ONE('_', 0, 0x25),
    TWO('`', G, 0x24, 0, 0x2C), /* `: dead ` +   */
    ONE('a', 0, 0x14),
    ONE('b', 0, 0x05),
    ONE('c', 0, 0x06),
    ONE('d', 0, 0x07),
    ONE('e', 0, 0x08),
    ONE('f', 0, 0x09),
    ONE('g', 0, 0x0A),
    ONE('h', 0, 0x0B),
    ONE('i', 0, 0x0C),
    ONE('j', 0, 0x0D),
    ONE('k', 0, 0x0E),
    ONE('l', 0, 0x0F),
    ONE('m', 0, 0x33),
    ONE('n', 0, 0x11),
    ONE('o', 0, 0x12),
    ONE('p', 0, 0x13),
    ONE('q', 0, 0x04),
    ONE('r', 0, 0x15),
    ONE('s', 0, 0x16),
    ONE('t', 0, 0x17),
    ONE('u', 0, 0x18),
    ONE('v', 0, 0x19),
    ONE('w', 0, 0x1D),
    ONE('x', 0, 0x1B),
    ONE('y', 0, 0x1C),
    ONE('z', 0, 0x1A),
    ONE('{', G, 0x21),
    ONE('|', G, 0x23),
    ONE('}', G, 0x2E),
    TWO('~', G, 0x1F, 0, 0x2C), /* ~: dead ~ +   */
    ONE(0x00A3, S, 0x30), /* £ */
    ONE(0x00A4, G, 0x30), /* ¤ */
    ONE(0x00A7, S, 0x38), /* § */
    TWO(0x00A8, S, 0x2F, 0, 0x2C), /* ¨: dead ¨ +   */
    ONE(0x00B0, S, 0x2D), /* ° */
    ONE(0x00B2, 0, 0x35), /* ² */
    ONE(0x00B5, S, 0x32), /* µ */
    TWO(0x00C0, G, 0x24, S, 0x14), /* À: dead ` + A */
    TWO(0x00C2, 0, 0x2F, S, 0x14), /* Â: dead ^ + A */
    TWO(0x00C3, G, 0x1F, S, 0x14), /* Ã: dead ~ + A */
    TWO(0x00C4, S, 0x2F, S, 0x14), /* Ä: dead ¨ + A */
    TWO(0x00C8, G, 0x24, S, 0x08), /* È: dead ` + E */
    TWO(0x00CA, 0, 0x2F, S, 0x08), /* Ê: dead ^ + E */
    TWO(0x00CB, S, 0x2F, S, 0x08), /* Ë: dead ¨ + E */
    TWO(0x00CC, G, 0x24, S, 0x0C), /* Ì: dead ` + I */
    TWO(0x00CE, 0, 0x2F, S, 0x0C), /* Î: dead ^ + I */
    TWO(0x00CF, S, 0x2F, S, 0x0C), /* Ï: dead ¨ + I */
    TWO(0x00D1, G, 0x1F, S, 0x11), /* Ñ: dead ~ + N */
    TWO(0x00D2, G, 0x24, S, 0x12), /* Ò: dead ` + O */
    TWO(0x00D4, 0, 0x2F, S, 0x12), /* Ô: dead ^ + O */
    TWO(0x00D5, G, 0x1F, S, 0x12), /* Õ: dead ~ + O */
    TWO(0x00D6, S, 0x2F, S, 0x12), /* Ö: dead ¨ + O */
    TWO(0x00D9, G, 0x24, S, 0x18), /* Ù: dead ` + U */
    TWO(0x00DB, 0, 0x2F, S, 0x18), /* Û: dead ^ + U */
    TWO(0x00DC, S, 0x2F, S, 0x18), /* Ü: dead ¨ + U */
    ONE(0x00E0, 0, 0x27), /* à */
    TWO(0x00E2, 0, 0x2F, 0, 0x14), /* â: dead ^ + a */
    TWO(0x00E3, G, 0x1F, 0, 0x14), /* ã: dead ~ + a */
    TWO(0x00E4, S, 0x2F, 0, 0x14), /* ä: dead ¨ + a */
    ONE(0x00E7, 0, 0x26), /* ç */
    ONE(0x00E8, 0, 0x24), /* è */
    ONE(0x00E9, 0, 0x1F), /* é */
    TWO(0x00EA, 0, 0x2F, 0, 0x08), /* ê: dead ^ + e */
    TWO(0x00EB, S, 0x2F, 0, 0x08), /* ë: dead ¨ + e */
    TWO(0x00EC, G, 0x24, 0, 0x0C), /* ì: dead ` + i */
    TWO(0x00EE, 0, 0x2F, 0, 0x0C), /* î: dead ^ + i */
    TWO(0x00EF, S, 0x2F, 0, 0x0C), /* ï: dead ¨ + i */
    TWO(0x00F1, G, 0x1F, 0, 0x11), /* ñ: dead ~ + n */
    TWO(0x00F2, G, 0x24, 0, 0x12), /* ò: dead ` + o */
    TWO(0x00F4, 0, 0x2F, 0, 0x12), /* ô: dead ^ + o */
    TWO(0x00F5, G, 0x1F, 0, 0x12), /* õ: dead ~ + o */
    TWO(0x00F6, S, 0x2F, 0, 0x12), /* ö: dead ¨ + o */
    ONE(0x00F9, 0, 0x34), /* ù */
    TWO(0x00FB, 0, 0x2F, 0, 0x18), /* û: dead ^ + u */
    TWO(0x00FC, S, 0x2F, 0, 0x18), /* ü: dead ¨ + u */
    TWO(0x00FF, S, 0x2F, 0, 0x1C), /* ÿ: dead ¨ + y */
    ONE(0x20AC, G, 0x08), /* € */
};

static bool keymap_fr_lookup(uint32_t cp, hid_seq_t *out)
{
    return keymap_table_lookup(keymap_fr_entries,
                               sizeof(keymap_fr_entries) / sizeof(keymap_fr_entries[0]), cp, out);
}

const keymap_layout_t keymap_fr = {
    .name   = "fr",
    .lookup = keymap_fr_lookup,
};
