/* United Kingdom Keyboard Layout (en-GB).
 *
 * GENERATED by tools/gen_keymap.py — edit the generator, not this file.
 * Source: This file was automatically generated by http://kbdlayout.info/ based on KBDTABLES
 * Source: of United Kingdom Keyboard Layout in kbduk.dll version 10.0.29580.1000.
 * via the KLC export of uk.klc, scancodes translated to HID usages.
 *
 * The AltGr column matches Windows and Linux, which both treat Right
 * Alt as AltGr for this layout. macOS builds its Option combinations
 * differently; on a macOS host those entries may come out wrong until
 * validated.
 */
#include "core/keymap.h"

#define S HID_MOD_LSHIFT
#define G HID_MOD_RALT

#define ONE(cp, m, k) {(cp), {{{(m), (k)}}, 1}}
#define TWO(cp, m1, k1, m2, k2) {(cp), {{{(m1), (k1)}, {(m2), (k2)}}, 2}}

static const keymap_entry_t keymap_uk_entries[] = {
    ONE('\t', 0, HID_KEY_TAB),
    ONE('\n', 0, HID_KEY_ENTER),
    ONE(' ', 0, 0x2C),
    ONE('!', S, 0x1E),
    ONE('"', S, 0x1F),
    ONE('#', 0, 0x32),
    ONE('$', S, 0x21),
    ONE('%', S, 0x22),
    ONE('&', S, 0x24),
    ONE('\'', 0, 0x34),
    ONE('(', S, 0x26),
    ONE(')', S, 0x27),
    ONE('*', S, 0x25),
    ONE('+', S, 0x2E),
    ONE(',', 0, 0x36),
    ONE('-', 0, 0x2D),
    ONE('.', 0, 0x37),
    ONE('/', 0, 0x38),
    ONE('0', 0, 0x27),
    ONE('1', 0, 0x1E),
    ONE('2', 0, 0x1F),
    ONE('3', 0, 0x20),
    ONE('4', 0, 0x21),
    ONE('5', 0, 0x22),
    ONE('6', 0, 0x23),
    ONE('7', 0, 0x24),
    ONE('8', 0, 0x25),
    ONE('9', 0, 0x26),
    ONE(':', S, 0x33),
    ONE(';', 0, 0x33),
    ONE('<', S, 0x36),
    ONE('=', 0, 0x2E),
    ONE('>', S, 0x37),
    ONE('?', S, 0x38),
    ONE('@', S, 0x34),
    ONE('A', S, 0x04),
    ONE('B', S, 0x05),
    ONE('C', S, 0x06),
    ONE('D', S, 0x07),
    ONE('E', S, 0x08),
    ONE('F', S, 0x09),
    ONE('G', S, 0x0A),
    ONE('H', S, 0x0B),
    ONE('I', S, 0x0C),
    ONE('J', S, 0x0D),
    ONE('K', S, 0x0E),
    ONE('L', S, 0x0F),
    ONE('M', S, 0x10),
    ONE('N', S, 0x11),
    ONE('O', S, 0x12),
    ONE('P', S, 0x13),
    ONE('Q', S, 0x14),
    ONE('R', S, 0x15),
    ONE('S', S, 0x16),
    ONE('T', S, 0x17),
    ONE('U', S, 0x18),
    ONE('V', S, 0x19),
    ONE('W', S, 0x1A),
    ONE('X', S, 0x1B),
    ONE('Y', S, 0x1C),
    ONE('Z', S, 0x1D),
    ONE('[', 0, 0x2F),
    ONE('\\', 0, 0x64),
    ONE(']', 0, 0x30),
    ONE('^', S, 0x23),
    ONE('_', S, 0x2D),
    ONE('`', 0, 0x35),
    ONE('a', 0, 0x04),
    ONE('b', 0, 0x05),
    ONE('c', 0, 0x06),
    ONE('d', 0, 0x07),
    ONE('e', 0, 0x08),
    ONE('f', 0, 0x09),
    ONE('g', 0, 0x0A),
    ONE('h', 0, 0x0B),
    ONE('i', 0, 0x0C),
    ONE('j', 0, 0x0D),
    ONE('k', 0, 0x0E),
    ONE('l', 0, 0x0F),
    ONE('m', 0, 0x10),
    ONE('n', 0, 0x11),
    ONE('o', 0, 0x12),
    ONE('p', 0, 0x13),
    ONE('q', 0, 0x14),
    ONE('r', 0, 0x15),
    ONE('s', 0, 0x16),
    ONE('t', 0, 0x17),
    ONE('u', 0, 0x18),
    ONE('v', 0, 0x19),
    ONE('w', 0, 0x1A),
    ONE('x', 0, 0x1B),
    ONE('y', 0, 0x1C),
    ONE('z', 0, 0x1D),
    ONE('{', S, 0x2F),
    ONE('|', S, 0x64),
    ONE('}', S, 0x30),
    ONE('~', S, 0x32),
    ONE(0x00A3, S, 0x20), /* £ */
    ONE(0x00A6, G, 0x35), /* ¦ */
    ONE(0x00AC, S, 0x35), /* ¬ */
    ONE(0x00C1, S|G, 0x04), /* Á */
    ONE(0x00C9, S|G, 0x08), /* É */
    ONE(0x00CD, S|G, 0x0C), /* Í */
    ONE(0x00D3, S|G, 0x12), /* Ó */
    ONE(0x00DA, S|G, 0x18), /* Ú */
    ONE(0x00E1, G, 0x04), /* á */
    ONE(0x00E9, G, 0x08), /* é */
    ONE(0x00ED, G, 0x0C), /* í */
    ONE(0x00F3, G, 0x12), /* ó */
    ONE(0x00FA, G, 0x18), /* ú */
    ONE(0x20AC, G, 0x21), /* € */
};

static bool keymap_uk_lookup(uint32_t cp, hid_seq_t *out)
{
    return keymap_table_lookup(keymap_uk_entries,
                               sizeof(keymap_uk_entries) / sizeof(keymap_uk_entries[0]), cp, out);
}

const keymap_layout_t keymap_uk = {
    .name   = "uk",
    .lookup = keymap_uk_lookup,
};
