/* Italian Keyboard Layout (it-IT).
 *
 * GENERATED by tools/gen_keymap.py — edit the generator, not this file.
 * Source: This file was automatically generated by http://kbdlayout.info/ based on KBDTABLES
 * Source: of Italian Keyboard Layout in kbdit.dll version 10.0.29580.1000.
 * via the KLC export of it.klc, scancodes translated to HID usages.
 *
 * The AltGr column matches Windows and Linux, which both treat Right
 * Alt as AltGr for this layout. macOS builds its Option combinations
 * differently; on a macOS host those entries may come out wrong until
 * validated.
 *
 * This layout cannot type these printable ASCII characters at all;
 * they resolve as KEYMAP_SKIPPED (a visible hole, never a wrong
 * character): ` ~
 */
#include "core/keymap.h"

#define S HID_MOD_LSHIFT
#define G HID_MOD_RALT

#define ONE(cp, m, k) {(cp), {{{(m), (k)}}, 1}}
#define TWO(cp, m1, k1, m2, k2) {(cp), {{{(m1), (k1)}, {(m2), (k2)}}, 2}}

static const keymap_entry_t keymap_it_entries[] = {
    ONE('\t', 0, HID_KEY_TAB),
    ONE('\n', 0, HID_KEY_ENTER),
    ONE(' ', 0, 0x2C),
    ONE('!', S, 0x1E),
    ONE('"', S, 0x1F),
    ONE('#', G, 0x34),
    ONE('$', S, 0x21),
    ONE('%', S, 0x22),
    ONE('&', S, 0x23),
    ONE('\'', 0, 0x2D),
    ONE('(', S, 0x25),
    ONE(')', S, 0x26),
    ONE('*', S, 0x30),
    ONE('+', 0, 0x30),
    ONE(',', 0, 0x36),
    ONE('-', 0, 0x38),
    ONE('.', 0, 0x37),
    ONE('/', S, 0x24),
    ONE('0', 0, 0x27),
    ONE('1', 0, 0x1E),
    ONE('2', 0, 0x1F),
    ONE('3', 0, 0x20),
    ONE('4', 0, 0x21),
    ONE('5', 0, 0x22),
    ONE('6', 0, 0x23),
    ONE('7', 0, 0x24),
    ONE('8', 0, 0x25),
    ONE('9', 0, 0x26),
    ONE(':', S, 0x37),
    ONE(';', S, 0x36),
    ONE('<', 0, 0x64),
    ONE('=', S, 0x27),
    ONE('>', S, 0x64),
    ONE('?', S, 0x2D),
    ONE('@', G, 0x33),
    ONE('A', S, 0x04),
    ONE('B', S, 0x05),
    ONE('C', S, 0x06),
    ONE('D', S, 0x07),
    ONE('E', S, 0x08),
    ONE('F', S, 0x09),
    ONE('G', S, 0x0A),
    ONE('H', S, 0x0B),
    ONE('I', S, 0x0C),
    ONE('J', S, 0x0D),
    ONE('K', S, 0x0E),
    ONE('L', S, 0x0F),
    ONE('M', S, 0x10),
    ONE('N', S, 0x11),
    ONE('O', S, 0x12),
    ONE('P', S, 0x13),
    ONE('Q', S, 0x14),
    ONE('R', S, 0x15),
    ONE('S', S, 0x16),
    ONE('T', S, 0x17),
    ONE('U', S, 0x18),
    ONE('V', S, 0x19),
    ONE('W', S, 0x1A),
    ONE('X', S, 0x1B),
    ONE('Y', S, 0x1C),
    ONE('Z', S, 0x1D),
    ONE('[', G, 0x2F),
    ONE('\\', 0, 0x35),
    ONE(']', G, 0x30),
    ONE('^', S, 0x2E),
    ONE('_', S, 0x38),
    ONE('a', 0, 0x04),
    ONE('b', 0, 0x05),
    ONE('c', 0, 0x06),
    ONE('d', 0, 0x07),
    ONE('e', 0, 0x08),
    ONE('f', 0, 0x09),
    ONE('g', 0, 0x0A),
    ONE('h', 0, 0x0B),
    ONE('i', 0, 0x0C),
    ONE('j', 0, 0x0D),
    ONE('k', 0, 0x0E),
    ONE('l', 0, 0x0F),
    ONE('m', 0, 0x10),
    ONE('n', 0, 0x11),
    ONE('o', 0, 0x12),
    ONE('p', 0, 0x13),
    ONE('q', 0, 0x14),
    ONE('r', 0, 0x15),
    ONE('s', 0, 0x16),
    ONE('t', 0, 0x17),
    ONE('u', 0, 0x18),
    ONE('v', 0, 0x19),
    ONE('w', 0, 0x1A),
    ONE('x', 0, 0x1B),
    ONE('y', 0, 0x1C),
    ONE('z', 0, 0x1D),
    ONE('{', S|G, 0x2F),
    ONE('|', S, 0x35),
    ONE('}', S|G, 0x30),
    ONE(0x00A3, S, 0x20), /* £ */
    ONE(0x00A7, S, 0x32), /* § */
    ONE(0x00B0, S, 0x34), /* ° */
    ONE(0x00E0, 0, 0x34), /* à */
    ONE(0x00E7, S, 0x33), /* ç */
    ONE(0x00E8, 0, 0x2F), /* è */
    ONE(0x00E9, S, 0x2F), /* é */
    ONE(0x00EC, 0, 0x2E), /* ì */
    ONE(0x00F2, 0, 0x33), /* ò */
    ONE(0x00F9, 0, 0x32), /* ù */
    ONE(0x20AC, G, 0x22), /* € */
};

static bool keymap_it_lookup(uint32_t cp, hid_seq_t *out)
{
    return keymap_table_lookup(keymap_it_entries,
                               sizeof(keymap_it_entries) / sizeof(keymap_it_entries[0]), cp, out);
}

const keymap_layout_t keymap_it = {
    .name   = "it",
    .lookup = keymap_it_lookup,
};
